### ISSUE TITLE
Doesn't reconnect on server restart

### ISSUE THREAD

**Issue by Zettin** [AMereBagatelle/AFKPeace#11]
The server I am on restarts daily it I had gotten this to afk my farms and not worry about the restart but it fails to log me back in.

**Comment by AMereBagatelle** [comment]
Are you sure the server is back up before the reconnection attempts run out?  If you can, try setting the `reconnectAttemptNumber` to a number >30 and `secondsBetweenReconnectAttempts` to a number >20.  This should make the mod try for much longer, and hopefully will have a better chance.

(I will be out of town for several days after this is posted, so don't expect a swift response :sweat_smile: )

**Comment by Zettin** [comment]
Thanks for the response I set my connection attempts to 9999 and the seconds between to 15. I'll try setting the seconds higher. Also don't worry I'm just glad you made this mod!

**Comment by TheonlyTazz** [comment]
im on a server that kicks you after 10minutes of afk... and the server doesnt allow you to reconnect to fast, else it'll put you in the hub... i wish the `secondsBetweenReconnectAttempts` would also work on the "first" reconnect... so, when you disconnect... wait n-seconds until first attempt and not (almost) immidiatly

**Comment by AMereBagatelle** [comment]
That's something I can fix.  I accidentally put the wait too late, and I'm not sure why.  Will be fixed in next release.  (Not going to close this report as I'm still waiting for the original poster)

**Comment by QuinnWede** [comment]
I'm having the same problem, the server I'm on restarts 2 hours after I go to bed so I can never get a full night of afking done. I've done the suggestions above but still every time I check in the morning it says the time of disconnect was 2 minutes after the server restart was scheduled and a timed out message. Any suggestions?

**Comment by AMereBagatelle** [comment]
You may want to try increasing the settings, as mentioned before.  This will allow the server more time to restart.

**Comment by AMereBagatelle** [comment]
This really isn't a forum, so for further help on this kind of issue, I am going to ask people to go to my discord where it is easier to give support directly.

https://discord.gg/quvzkaV

**Comment by QuinnWede** [comment]
Thanks!
