### ISSUE TITLE
Config resets on every minecraft loadup.

### ISSUE THREAD

**Issue by Kichura** [AMereBagatelle/AFKPeace#12]
When configuring the afk-peace config using in-game commands, It gets saved for each setting set.

But rebooting the client (and likely connecting to a server i assume) resets the entire config back to default so that user has to redo the entire commands again for another session.

**Comment by AMereBagatelle** [comment]
Can you provide a log during which you attempted to save settings?  They seem to save correctly on my local machine.

**Comment by Kichura** [comment]
^ I have checked the logs and it only contained the chat saying that the afk commands have been set successfully, But when MC is booted back up the log shows no reports of afkpeace erroring out (or corrupted file); However notepad++ complains that the file has been modified and that the settings have been reset to factory settings.

**Comment by AMereBagatelle** [comment]
I successfully reproduced the problem.  I believe I simply flipped a null check, will be fixed in next release.
