### ISSUE TITLE
Auto-reply AFK

### ISSUE THREAD

**Issue by IpsoValvo** [AMereBagatelle/AFKPeace#13]
Enhancement so it auto-replies "I am AFK" whenever someone tries to chat would be awesome! I can't find anything anywhere like that!

**Comment by AMereBagatelle** [comment]
Interesting idea, but how would you know if someone addresses something to you?  It could get spammy, potentially.  I do agree that a AFK indicator would be a good idea, though.

**Comment by IpsoValvo** [comment]
Ohhhh, I forgot the chat is public! 🤣 We play on a private server, with 5
people max! So, spamming is not a problem for us!

How about in the GUI you can turn on if your AFK, and if anyone wants to
know, they can type something like “/AFKPeace isAFK [player]”? That way
they know if you are AFK or not without spamming!

**Comment by AMereBagatelle** [comment]
I've decided not to implement this, as all the good ways to do this are either server-side or very clunky.
There are other ways to do this as well, such as the Vanilla Tweaks packs: https://vanillatweaks.net/picker/datapacks/
