### ISSUE TITLE
Cannot rejoin Realms

### ISSUE THREAD

**Issue by AMereBagatelle** [AMereBagatelle/AFKPeace#14]
Realms use a different protocol to the standard MC connection protocol, and so will require special support.

**Comment by MariusAlbrecht** [comment]
I would also be interested in this feature. If the rejoining is not easily possible just throwing me out in the home or realms menu and not the server list would be nice too.

**Comment by AMereBagatelle** [comment]
Update on this issue.

I see where I could attempt to hack into the realms protocol to allow this, however I do not have a realms server to test this on.  I don't plan on buying a Realms server, so I'll leave this open to external contributions.

**Comment by AMereBagatelle** [comment]
Closing as not planned.  If anyone has a realms server and wants to attempt to get this working, please PR it upstream.
