### ISSUE TITLE
Integer casting to String

### ISSUE THREAD

**Issue by Crazy-Techie** [AMereBagatelle/AFKPeace#16]
So I was starting up minecraft right after adding the mod and I got this crash report which says that it crashed because it was trying to cast an integer as a string. I have the crash report attached.

[crash-2021-03-07_20.35.37-client.txt](https://github.com/AMereBagatelle/AFKPeace/files/6098830/crash-2021-03-07_20.35.37-client.txt)

**Comment by AMereBagatelle** [comment]
Fixed in latest release.

**Comment by Crazy-Techie** [comment]
[crash-2021-03-08_18.36.48-client.txt](https://github.com/AMereBagatelle/AFKPeace/files/6105207/crash-2021-03-08_18.36.48-client.txt)
That wasn't everything.

**Comment by AMereBagatelle** [comment]
Alright, well I'll take another good look at it tomorrow

**Comment by AMereBagatelle** [comment]
Took another look at your crash log, it looks like you are still using version 4.6.1.  Please update :P

**Comment by Crazy-Techie** [comment]
[crash-2021-03-09_18.43.05-client.txt](https://github.com/AMereBagatelle/AFKPeace/files/6112556/crash-2021-03-09_18.43.05-client.txt)
Updated, newest crash report.

**Comment by AMereBagatelle** [comment]
Whoops, forgot to include the library I was using.  So sorry for all the trouble!  (I won't be able to release another build until tomorrow, so if you want to use the mod tonight, install the library from https://github.com/AMereBagatelle/Disabler/releases)

**Comment by Crazy-Techie** [comment]
Ok, got it working

**Comment by MightyKnight** [comment]
@AMereBagatelle Might want to do a release soon, was just about to create another issue when I found this^^.
Not everyone will go searching on Github if it crashes.
