### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [AMereBagatelle/AFKPeace#17]
This is the only mod. Fabric loader 0.11.2.
crash report: https://gist.github.com/DragonEggBedrockBreaking/f11224f3262f570bc59276a98a66007a

**Comment by AMereBagatelle** [comment]
Duplicate of #16

**Comment by DragonEggBedrockBreaking** [comment]
> Duplicate of #16

Oh, sorry.
