### ISSUE TITLE
Crash when joining aternos server with the Origin mod

### ISSUE THREAD

**Issue by barraIhsan** [AMereBagatelle/AFKPeace#19]
So when i want to play in aternos server suddenly my client crash, so usually I turn off the afkpeace and it work. But I don't know if I also install origin mod, it crash? Crash report :
https://gist.githubusercontent.com/natanfudge/e6fae9282f444d712635dcb684cf5cfa/raw/64fce1fcd8d12efe755981c411035c889a896368/crash.txt

**Comment by AMereBagatelle** [comment]
Please clarify, the crash only happens when you connect to your Aternos server with both Origins and AFKPeace installed?

**Comment by barraIhsan** [comment]
Yes i think. Also there is some line to clarify is it because afkPeace
`at amerebagatelle.github.io.afkpeace.AFKPeaceClient.lambda$onInitializeClient$1(AFKPeaceClient.java:36)`

**Comment by barraIhsan** [comment]
Also with aternos, I think they disable AFKPeace. When I join aternos server my logs say that the AFK has been turned off. Maybe because of that too?

**Comment by AMereBagatelle** [comment]
The latest commit should fix this issue.  You can get the build from build artifacts or wait for the next release.
