### ISSUE TITLE
Suggestion, prevent afk by hitting once

### ISSUE THREAD

**Issue by RasmusKD** [AMereBagatelle/AFKPeace#20]
Set an interval to when your user hits once out in the air, preventing him from being kicked by anti-AFK plugins. It would also be helpful to set a random gap between x and x min, so if I were to set it to 10/20 min, he could randomly hit 14:37 into being AFK, then the random interval should restart and do until turned off

**Comment by AMereBagatelle** [comment]
I'm not interested in purposefully circumventing Anti-AFK plugins and never will.  If you look at the [README](https://github.com/AMereBagatelle/AFKPeace#server-settings), I even added a feature so that the mod can be disabled by server owners.
