### ISSUE TITLE
Cannot join big servers

### ISSUE THREAD

**Issue by JustAlittleWolf** [AMereBagatelle/AFKPeace#21]
With this mod installed (the only other mod i had in my mods folder was the fabric api) you are unable to play on servers like hypixel.

**Comment by supsm** [comment]
What happens when you try to join? Do you have any logs?

**Comment by JustAlittleWolf** [comment]
It kicks me back into the limbo lobby.
This is the log without modmenu (i only noticed that it requires modmenu after looking at the logs)
https://pastebin.com/8EfUTYvk

Once I added modmenu it let me join and interact but blocks had no collision and i just flew through them? (Adventure mode) This only happened once and I couldn't replicate it.
I disconnected and tried to join again but with no success similar to when i hadn't had modmenu installed.
https://pastebin.com/n535ZGaQ

**Comment by AMereBagatelle** [comment]
This issue looks a tad... familiar to me.  From the logs, I don't believe there's a ton I can do to fix this.  It looks like Hypixel is sending an invalid packet over the network.

**Comment by supsm** [comment]
Ah yes, there's a similar issue with lambdacontrols (logs look a bit different). Hypixel uses very cursed networking, so it doesn't work with some mods

**Comment by SunnySlopes** [comment]
i've encountered similar questions here, and here's my crash report:
[crash-2021-04-26_09.16.32-client.txt](https://github.com/AMereBagatelle/AFKPeace/files/6373728/crash-2021-04-26_09.16.32-client.txt)

**Comment by AMereBagatelle** [comment]
At the current state, I don't believe there's anything I can do about Hypixel's broken networking and so will close this issue.

**Comment by cootshk** [comment]
i had this issue acciedentially joining 2b2t
my crash log: https://crashy.net/hgfFdPtUzQIxWCm2URVH
