### ISSUE TITLE
Crash on server join

### ISSUE THREAD

**Issue by UltraBlackLinux** [AMereBagatelle/AFKPeace#22]
Hey there,
AfkPeace is crashing my client, whenever I am trying to join - here are my logs: https://paste.ee/p/Dz1uf
Are you able to fix this?
Thanks!

**Comment by AMereBagatelle** [comment]
This issue should be fixed with the current latest commit, it just hasn't been released yet.  You can get the latest build from [Github Actions](https://github.com/AMereBagatelle/AFKPeace/actions/runs/684716698) or simply wait for the next release.
