### ISSUE TITLE
Forge support?

### ISSUE THREAD

**Issue by A-Random-Lemon** [AMereBagatelle/AFKPeace#25]
It'd be nice if there was a forge version as there are like 3 different versions of this mod by different people for fabric while there are none for forge.

**Comment by supsm** [comment]
n o.
[random comment which is related](https://www.curseforge.com/minecraft/mc-mods/requiem?comment=358)

**Comment by AMereBagatelle** [comment]
Simple answer, no.
Long answer for future readers, I don't support Forge because it would require lots of extra work on my part, for little reward from my perspective.
