### ISSUE TITLE
Maintained fork without server disable-ability.

### ISSUE THREAD

**Issue by mikenrafter** [AMereBagatelle/AFKPeace#26]
Some people don't like playing fair, that's their deal, there are other ways to achieve this functionality, but this mod is nice.
There's currently a fork with the disable API, well, disabled. I think that either: A, this should become the default functionality; B, this should be a configurable option; C, make and maintain a fork that doesn't bother with any of that moderator-assist stuff.

Now, I could do it myself, but I think that others would agree: people should have a choice in the matter, and if they want to hack, let them, there's anti-cheats out there for a reason, just leave it so.

**Comment by AMereBagatelle** [comment]
For me, allowing server owners to disable these functionalities that are commonly banned on public servers is a matter of personal morality.  I put the disabling function there for a reason.  To your last point, people do have a choice, to fork the mod.
