### ISSUE TITLE
Loggin me out on death when not AFK

### ISSUE THREAD

**Issue by YumatanGames** [AMereBagatelle/AFKPeace#28]
I'm having an issue with this mod, when it keeps logging me out on death even when I'm not afk. I even try disabling the "logout on damage", but it seems to be ignoring it.

**Comment by AMereBagatelle** [comment]
Can you reproduce the issue with AutoAFK off?  It is possible that AutoAFK is not properly resetting the values when you begin moving.

**Comment by ErrorNoInternet** [comment]
Happens to me too when someone kills me (I get disconnected whenever I get killed or really low)

**Comment by AMereBagatelle** [comment]
Since I cannot reproduce this issue, until I get reproduction steps this issue will be closed.
