### ISSUE TITLE
crash upon joining a server

### ISSUE THREAD

**Issue by cootshk** [AMereBagatelle/AFKPeace#31]
crash report: https://crashy.net/hgfFdPtUzQIxWCm2URVH

**Comment by AMereBagatelle** [comment]
Can you detail the full reproduction steps?  I can't just guess at what caused the error here.

**Comment by cootshk** [comment]
Basically

**Comment by cootshk** [comment]
Basically I joined 2b2t (a 1.12 server). I assume that the wrong version kick showed up, but then afk peace tried to reconnect (many times). This overflow crashed minecraft. Steps to replicate: join a server either on the wrong version or a server that is down for maintenance.

**Comment by AMereBagatelle** [comment]
I cannot reproduce on my machine with the latest dev branch.  Is this issue consistent?

**Comment by AMereBagatelle** [comment]
Is this still an issue?  I will close this in 2 days if no response (if I remember).
