### ISSUE TITLE
Damage Logout when not afk, and doesn't save settings

### ISSUE THREAD

**Issue by TaklaPro** [AMereBagatelle/AFKPeace#32]
I have a problem where it damage logs me out when not AFK, also I have it disabled but it save's settings until the game is closed and will reenable damage logout when starting the game, Any help would be great!

**Comment by AMereBagatelle** [comment]
It is possible this is fixed with the just-released 4.7.1.  Can you test please?  Also, ensure that you are clicking the "Save" button at the bottom of the config screen whenever you are done editing settings.

**Comment by TaklaPro** [comment]
Sure Imma test it and will let you know! Also I am pressing the save button.

**Comment by TaklaPro** [comment]
It didn't fix it but minimized it for sure!

**Comment by hens50** [comment]
Same issue here!

**Comment by The-Gmann** [comment]
Same problem

**Comment by LeigerGaming** [comment]
Installed 4.7.1 and I have the same issue. Falling off scaffolding and losing a couple hearts led to me leaving the server due to damage, even though I wasn't AFK (I had been actively building for the past 20 minutes before that).

Minecraft 1.18.1 Fabric client, the server runs PaperMC.

**Comment by vladbogun1** [comment]
ye, same bug, please fix that)

**Comment by vladbogun1** [comment]
I fixed that for myself changing || to && here:
![image](https://user-images.githubusercontent.com/34967580/174332058-a5bb9a5b-37f3-499f-b7d8-b64f665d5069.png)
So in this case you will be logged out only during afk and damage

**Comment by AMereBagatelle** [comment]
I believe this is actually a simple misinterpretation of what the AFK mode does.  The AFK mode enables all features regardless of whether their option is actually on (I plan to change the config to allow this to be more configurable in the future).  This means that if the damage logout setting is on, damage logout will be on regardless of whether you are AFK.  I apologize that this is not more clear.

**Comment by AMereBagatelle** [comment]
This issue has been addressed better in the latest commit.
