### ISSUE TITLE
Fabric Version of the Mod (enhancement)

### ISSUE THREAD

**Issue by Timongcraft** [AMereBagatelle/AFKPeace#39]
Readd fabric compartiplisity or add a fabric version of  the mod.
Would be nice to have, but no preasure and no must.

**Comment by supsm** [comment]
I don't think this is planned for the mod unfortunately, but [I did make a fork](https://github.com/supsm/AFKPeace-fabric) (shameless self plug) (also it isn't 100% complete yet)

**Comment by AMereBagatelle** [comment]
Not planned.  I moved to Quilt for the config library and I don't plan to move back (I don't think Quilt Config is compatible with Fabric, either).

**Comment by luni3359** [comment]
@supsm thank you so much I'm looking forward to it

**Comment by Timongcraft** [comment]
Ok
