### ISSUE TITLE
Doesnt rejoin on Damage Logout

### ISSUE THREAD

**Issue by Locho18** [AMereBagatelle/AFKPeace#4]
When the Damage Logout is enabled it doesnt automatically rejoin the server or single player world

**Comment by AMereBagatelle** [comment]
This is as intended.  Damage logout would be useless if it logged you right back into the world, as whatever damaged you would still be there.

**Comment by Locho18** [comment]
So i cant have both on at the same time?

**Comment by Locho18** [comment]
I would like to have the option to have them both on so if say a zombie attacked me it would make me leave and then when i rejoin the zombie would have despawned

**Comment by AMereBagatelle** [comment]
I can add a option to turn them both on, it will go on the todo list.

**Comment by Locho18** [comment]
Thanks
That will be a good addon

**Comment by AMereBagatelle** [comment]
I have now included this in the newest release on CurseForge. [https://www.curseforge.com/minecraft/mc-mods/afkpeace/files/2994117](https://www.curseforge.com/minecraft/mc-mods/afkpeace/files/2994117)
