### ISSUE TITLE
1.20 version is published under 1.19.4 and causes issues installing

### ISSUE THREAD

**Issue by BlackWolfWoof** [AMereBagatelle/AFKPeace#48]
The 1.20 version 6.1.0 is released for the version 1.19.4 and installing it crashes minecraft on startup.
Please change the version to strictly only work on 1.20
![image](https://github.com/AMereBagatelle/AFKPeace/assets/29355595/c498905a-f0b8-4976-ae58-05e7f80c4a1b)

**Comment by AMereBagatelle** [comment]
Oop.
