### ISSUE TITLE
Damage tolerance

### ISSUE THREAD

**Issue by spiprod** [AMereBagatelle/AFKPeace#5]
Sometimes, when you afk at mobfarms, a mob with thorns armor could spawn and end your afk session abruptly if you have damage-logging enabled. So i propose a threshhold for the amount of lives the player has to have for the damagelog to trigger. you could even make the player eat any food it has upon taking minor damage to regenerate

**Comment by AMereBagatelle** [comment]
I have now included this in the newest release on CurseForge. [https://www.curseforge.com/minecraft/mc-mods/afkpeace/files/2994117](https://www.curseforge.com/minecraft/mc-mods/afkpeace/files/2994117)
