### ISSUE TITLE
SpruceUI causing crashes on 1.20.6

### ISSUE THREAD

**Issue by AMereBagatelle** [AMereBagatelle/AFKPeace#50]
It seems I was hasty in updating to 1.20.6, with the SpruceUI dependency.  Attempting to type into the textboxes in 1.20.6 crashes the game.  I will keep an eye on this, but the only real fix is for SpruceUI to update.  If it has not been updated by the time 1.21 releases, I will rewrite the GUI systems (again).

Watching PR in SpruceUI: [#51](https://github.com/LambdAurora/SpruceUI/pull/51)

**Comment by LambdAurora** [comment]
SpruceUI has been updated for both 1.20.6 and 1.21.

**Comment by AMereBagatelle** [comment]
Thanks!
