### ISSUE TITLE
Autolog

### ISSUE THREAD

**Issue by pizzav-xyz** [AMereBagatelle/AFKPeace#51]
Disconnect when low

**Comment by AMereBagatelle** [comment]
I'm going to need more information than that (e.g. what actually is the issue, is this a feature request, what do you want to happen that's not happening, etc etc).  Closing until more information is received.

**Comment by pizzav-xyz** [comment]
> I'm going to need more information than that (e.g. what actually is the issue, is this a feature request, what do you want to happen that's not happening, etc etc). Closing until more information is received.

feature request

**Comment by AMereBagatelle** [comment]
Still not even _near_ enough information.  If you have a full feature request, please look at some of the open feature requests on this repository for examples of enough information and open a new issue.  I can't read your mind, if you don't say it I don't know it.
