### ISSUE TITLE
Crash when leaving the game afk for long

### ISSUE THREAD

**Issue by calloatti** [AMereBagatelle/AFKPeace#8]
https://paste.ee/p/Z2CLp

**Comment by calloatti** [comment]
Also, is this the mod too? 

![](https://user-images.githubusercontent.com/12817862/87655586-d7226500-c72e-11ea-9092-2649417aa25c.png)

**Comment by AMereBagatelle** [comment]
I probably should move that reconnect button to be more reactive, or just more out of the way.  I assume you've figured out the crash then?

**Comment by calloatti** [comment]
No, not figured out the crash. But will do more testing and upload a multimc instance so you can reproduce
